harnessApiVersion: '1.0'
type: GIT
branch: config
keyAuth: true
providerType: GIT
sshKeyName: kaizen-github-config-ssh
url: git@github.com:P434585/kaizen-java-bg-trigger.git
urlType: REPO
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
