harnessApiVersion: '1.0'
type: GIT
branch: SISLE-5140-Harness-CD-config
keyAuth: true
sshKeyName: sl-ssh-key
url: git@github.com:nationwide-building-society/sl-deploy-environment-provisioning.git
urlType: REPO
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - PROD
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
