harnessApiVersion: '1.0'
type: GIT
keyAuth: true
providerType: GIT
sshKeyName: vaidy-ssh-config
url: git@github.com:nationwide-building-society/kaizen-helloworld-java.git
urlType: REPO
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - PROD
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
