harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: 'This is to verify CV integration with harness. '
envName: dev-canary
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Lh9O151sSmC3_XapvUbb-w
phases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: uJ0NZrvSTpCcC3PtWZf7HQ
        analysisTolerance: HIGH
        comparisonStrategy: COMPARE_WITH_CURRENT
        customThresholdRefId: 088d468e864c4969accf7868006b568c
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 5
        timeSeriesToAnalyze:
        - metricName: CPU-throughput
          metricType: RESP_TIME
          txnName: hardware
          url: container_cpu_usage_seconds_total{namespace="kaizen-testing-1",pod="$hostName",container="prometheus"}
        - metricName: CPU-error
          metricType: THROUGHPUT
          txnName: hardware
          url: container_cpu_usage_seconds_total{namespace="kaizen-testing-1",pod="$hostName",container="prometheus"}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
      properties:
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Phase 3
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: EMAIL
      name: Email
      properties:
        body: hey
        ccAddress: shwetha.ballari@nationwide.co.in
        subject: phase-2 canary deployment testing
        toAddress: akash.gupta@nationwide.co.uk
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
preDeploymentSteps:
- type: EMAIL
  name: Akash Gupta
  properties:
    body: Hey
    ccAddress: manbir.bhullar@nationwide.co.uk
    subject: 'Canary deployment trigger '
    toAddress: akash.gupta@nationwide.co.uk
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Primary
  phaseNameForRollback: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Phase 3
  phaseNameForRollback: Phase 3
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
templatized: false
