harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: 'This is to verify CV integration with harness. '
envName: dev-canary
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Lh9O151sSmC3_XapvUbb-w
phases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
preDeploymentSteps:
- type: EMAIL
  name: Akash Gupta
  properties:
    body: Hey
    ccAddress: manbir.bhullar@nationwide.co.uk
    subject: 'Canary deployment trigger '
    toAddress: akash.gupta@nationwide.co.uk
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
templatized: false
