harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: 'This is to verify CV integration with harness. '
envName: dev-canary
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Lh9O151sSmC3_XapvUbb-w
preDeploymentSteps:
- type: EMAIL
  name: Akash Gupta
  properties:
    body: Hey
    ccAddress: manbir.bhullar@nationwide.co.uk
    subject: 'Canary deployment trigger '
    toAddress: akash.gupta@nationwide.co.uk
templatized: false
